@startuml

title __CORE's Class Diagram__\n

  namespace princess.connect {
    namespace core {
      class princess.connect.core.Audio {
          {static} + DEFAULT_LEFT_VOLUME : int
          {static} + DEFAULT_RIGHT_VOLUME : int
          - _player : MediaPlayer
          + Audio()
          + Audio()
          + loadAudio()
          + loadAudio()
          + pause()
          + play()
          + release()
          + resume()
          + setRepeating()
          + stop()
      }
    }
  }
  

  namespace princess.connect {
    namespace core {
      class princess.connect.core.MovingBitmap {
          - _bitmap : Bitmap
          - _height : int
          - _matrixRotate : Matrix
          - _matrixScale : Matrix
          - _matrixShow : Matrix
          - _matrixTranslate : Matrix
          - _visible : boolean
          - _width : int
          - _x : int
          - _y : int
          + MovingBitmap()
          + MovingBitmap()
          + MovingBitmap()
          + MovingBitmap()
          + MovingBitmap()
          + MovingBitmap()
          + crop()
          + getHeight()
          + getWidth()
          + getX()
          + getY()
          + inversion()
          + loadBitmap()
          + loadBitmap()
          + loadBitmap()
          + loadBitmap()
          + move()
          + release()
          + resize()
          + resize()
          + rotate()
          + setLocation()
          + setVisible()
          + show()
      }
    }
  }
  

  namespace princess.connect {
    namespace core {
      class princess.connect.core.SoundEffects {
          {static} + DEFAULT_LEFT_VOLUME : float
          {static} + DEFAULT_LOAD_PRIORITY : int
          {static} + DEFAULT_MAXIMUM_STREAMS : int
          {static} + DEFAULT_PLAYBACK_RATE : float
          {static} + DEFAULT_PLAY_PRIORITY : int
          {static} + DEFAULT_REPEAT_TIMES : int
          {static} + DEFAULT_RIGHT_VOLUME : float
          {static} + DEFAULT_SOUND_QUALITY : int
          {static} + MAXIMUM_PLAYBACK_RATE : float
          {static} + MINIMUM_PLAYBACK_RATE : float
          - _playedSounds : HashMap<Integer, Integer>
          - _sounds : SoundPool
          - _soundsMap : HashMap<Integer, Integer>
          + SoundEffects()
          + addSoundEffect()
          + addSoundEffect()
          + pause()
          + play()
          + play()
          + play()
          + release()
          + resume()
          + stop()
      }
    }
  }
  

  princess.connect.core.Audio .up.|> princess.connect.ReleasableResource
  princess.connect.core.MovingBitmap .up.|> princess.connect.GameObject
  princess.connect.core.SoundEffects .up.|> princess.connect.ReleasableResource


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
